title: AI for Cybersecurity\: A Handbook of Use Cases
description: By [Peng Liu](https://s2.ist.psu.edu/pliu/), Tao Liu, [Nanqing Luo](https://sites.google.com/view/nanqingluo/home), Zitong Shang, Haizhou Wang, [Zhilong Wang](http://zhilongwang.org/), Lan Zhang, and Qingtian Zou From [Penn State Cybersecurity Lab](https://s2.ist.psu.edu/index.html).


# Build settings
markdown: kramdown
theme: jekyll-theme-modernist
plugins:
  - jekyll-feed
